// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MadkDE.Models;

public partial class Material
{
    public int MaterialId { get; set; }

    public string Name { get; set; }

    public int MaterialTypeId { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal QuantityInStock { get; set; }

    public decimal MinQuantity { get; set; }

    public int QuantityPerPackage { get; set; }

    public string Unit { get; set; }

    public virtual ICollection<MaterialSupplier> MaterialSuppliers { get; set; } = new List<MaterialSupplier>();

    public virtual MaterialType MaterialType { get; set; }
}