// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MadkDE.Models;

public partial class MaterialType
{
    public int MaterialTypeId { get; set; }

    public string Name { get; set; }

    public decimal WastePercentage { get; set; }

    public virtual ICollection<Material> Materials { get; set; } = new List<Material>();
}