// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MadkDE.Models;

public partial class MaterialSupplier
{
    public int MaterialId { get; set; }

    public int SupplierId { get; set; }

    public virtual Material Material { get; set; }

    public virtual Supplier Supplier { get; set; }
}