// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MadkDE.Models;

public partial class ProductType
{
    public int ProductTypeId { get; set; }

    public string Name { get; set; }

    public decimal Coefficient { get; set; }
}