// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MadkDE.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string Name { get; set; }

    public string SupplierType { get; set; }

    public string Inn { get; set; }

    public int? Rating { get; set; }

    public DateOnly StartDate { get; set; }

    public virtual ICollection<MaterialSupplier> MaterialSuppliers { get; set; } = new List<MaterialSupplier>();
}